#!/bin/sh

#
# Installation script
#
# 1) cp impcmpload.config.default impcmpload.config
# 2) cp impclaczload.config.default impclaczload.config
# 2) Install 
#

Usage=Install

#
#  Function called when the install fails.
#
installFailed ()
{
    echo "Installation Failed: `date`"
    exit 1
}

#
#  Verify the arguments to the script, there shouldn't be any
#
if [ $# -ne 0 ]
then
    echo "Usage: ${Usage}"
    installFailed
fi

#
#  If the MGICONFIG environment variable does not have a local override,
#  use the default "live" settings.
#
if [ "${MGICONFIG}" = "" ]
then
    MGICONFIG=/usr/local/mgi/live/mgiconfig
    export MGICONFIG
fi

# establish name of master config and source it
. ${MGICONFIG}/master.config.sh

cd `dirname $0`

# Check to see if this is a development installation
#
DEV=""
if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi

COMMON_CONFIG=common.config

if [ ! -r ${COMMON_CONFIG} ]
then
    echo "Missing configuration file: ${COMMON_CONFIG}"
    installFailed
fi

#
# Source the common configuration file.
#
. ${COMMON_CONFIG}

#
# run DLAInstall for each configuration file
#
echo "HTMPLOAD: ${HTMPLOAD}"
echo ${HTMPLOAD}/[d-z]*config
for c in ${HTMPLOAD}/[d-z]*config ${HTMPLOAD}/test/impcmpload.config.test
do

echo 'running DLAINSTALL:' ${c}
. ${c}
${DLAINSTALL} ${DEV}

#
# Create the input directory if it doesn't exist.
#
if [ ! -d ${INPUTDIR} ]
then
    mkdir -p ${INPUTDIR}
fi
#
# Create the postMP directory if it doesn't exist.
#
if [ ! -d ${POSTMPLOGDIR} ]
then
    mkdir -p ${POSTMPLOGDIR}
fi

done
